name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Hello world
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'

    - name: Build the code
      run: 'dotnet build'

    - name: Tests the code
      run: 'dotnet test'

    - name: Builds the TypeScript code part 1
      working-directory: './DotnetTemplate.Web'
      run: 'npm install'

    - name: Builds the TypeScript code part 2
      working-directory: './DotnetTemplate.Web' 
      run: 'npm run build'

    - name: Runs the linter
      working-directory: './DotnetTemplate.Web' 
      run: 'npm t'

    - name: Runs the TypeScript tests
      working-directory: './DotnetTemplate.Web'
      run: 'npm run lint'


